<?php

/**
 * @file
 * Module file for the OSU Groups module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Most of this code was taken from the Drupal Redirect module.
 */
function osu_groups_form_group_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // phpcs:disable
  /* Theme Form options if drupal.org/i/3441929 is closed
  $form['#theme'] = ['group_edit_form'];
  $form['#attached']['library'][] = 'claro/node-form';
  $form['advanced']['#type'] = 'container';
  $form['advanced']['#accordion'] = TRUE;
  $form['meta']['#type'] = 'container';
  $form['meta']['#access'] = TRUE;
  $form['revision_information']['#type'] = 'container';
  $form['revision_information']['#group'] = 'meta';
  $form['revision_information']['#attributes']['class'][] = 'entity-meta__revision';
   */
  // phpcs:enable
  /** @var \Drupal\group\Entity\GroupInterface $group */
  $group = $form_state->getFormObject()->getEntity();
  // Ensure that we are not on a New group and that the user has the correct
  // permission.
  if (!$group->isNew() && \Drupal::currentUser()
      ->hasPermission('administer redirects')) {
    $gid = $group->id();
    // Find redirects to this group.
    $redirects = \Drupal::service('redirect.repository')
    ->findByDestinationUri(["internal:/group/$gid", "entity:group/$gid"]);
    // Assemble the rows for the table.
    $rows = [];
    /** @var \Drupal\Core\Entity\EntityListBuilder $list_builder */
    $list_builder = \Drupal::service('entity_type.manager')
      ->getListBuilder('redirect');
    /** @var \Drupal\redirect\Entity\Redirect[] $redirects */
    foreach ($redirects as $redirect) {
      $row = [];
      $path = $redirect->getSourcePathWithQuery();
      $row['path'] = [
        'class' => ['redirect-table__path'],
        'data' => ['#plain_text' => $path],
        'title' => $path,
      ];
      $row['operations'] = [
        'data' => [
          '#type' => 'operations',
          '#links' => $list_builder->getOperations($redirect),
        ],
      ];
      $rows[] = $row;
    }
    // Add the list to the vertical tabs section of the form.
    $header = [
      ['class' => ['redirect-table__path'], 'data' => t('From')],
      ['class' => ['redirect-table__operations'], 'data' => t('Operations')],
    ];

    $form['url_redirects'] = [
      '#type' => 'details',
      '#title' => t('URL redirects'),
      '#group' => 'advanced',
      '#open' => FALSE,
      'table' => [
        '#type' => 'table',
        '#header' => $header,
        '#rows' => $rows,
        '#empty' => t('No URL redirects available.'),
        '#attributes' => ['class' => ['redirect-table']],
      ],
      '#attached' => [
        'library' => [
          'redirect/drupal.redirect.admin',
        ],
      ],
    ];
    if (!empty($rows)) {
      $form['url_redirects']['warning'] = [
        '#markup' => t('Note: links open in the current window.'),
        '#prefix' => '<p>',
        '#suffix' => '</p>',
      ];
    }

    $form['url_redirects']['actions'] = [
      '#theme' => 'links',
      '#links' => [],
      '#attributes' => ['class' => ['action-links']],
    ];
    $form['url_redirects']['actions']['#links']['add'] = [
      'title' => t('Add URL redirect'),
      'url' => Url::fromRoute('redirect.add', [
        'redirect' => $group->toUrl()->getInternalPath(),
        'destination' => \Drupal::destination()->get(),
      ]),
      'attributes' => [
        'class' => [
          'button',
        ],
        'target' => '_blank',
      ],
    ];
  }
}
