<?php

/**
 * @file
 * Primary module hooks for OSU Media module.
 */

use Drupal\osu_media\Entity\Bundle\MediaImage;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function osu_media_entity_bundle_info_alter(array &$bundles): void {
  /*
   * Add a bundle wrapper for Media Image to force the Thumbnail alt text to
   * update.
   *
   * Corresponding issues
   * https://www.drupal.org/project/drupal/issues/3232414
   * https://www.drupal.org/project/drupal/issues/2983456
   * https://www.drupal.org/project/drupal/issues/3088168
   */
  if (isset($bundles['media']['image'])) {
    $bundles['media']['image']['class'] = MediaImage::class;
  }
}
