#!/usr/bin/env bash
set -e
if [ -z "${DRUPAL_THEME_DEVEL}" ]; then
  echo "Running in Production Mode"
  composer update osulp/osulp-drupal-subtheme && drush cr &
else
  cp /var/www/html/docroot/sites/default/default.services.yml /var/www/html/docroot/sites/default/services.yml
  sed -i 's/debug\:\ false/debug\:\ true/' /var/www/html/docroot/sites/default/services.yml
  sed -i 's/auto_reload\:\ null/auto_reload\:\ true/' /var/www/html/docroot/sites/default/services.yml
  sed -i 's/cache\:\ true/cache\:\ false/' /var/www/html/docroot/sites/default/services.yml
  echo "Finished setting up Theme Development Settings."
fi
exec "$@"
