services:
  mariadb:
    image: wodby/mariadb:10.11-3.28.3
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_TRANSACTION_ISOLATION: READ-COMMITTED
    volumes:
      - ./dev/mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - mariadb:/var/lib/mysql # Use bind mount

  apache:
    build:
      context: .
      target: development
    platform: linux/amd64
    depends_on:
    - mariadb
    ports:
    - 3000:80
    environment:
      # By default xdebug extension also disabled.
      PHP_EXTENSIONS_DISABLE: xhprof,spx
      PHP_MAIL_MIXED_LF_AND_CRLF: On
      DRUPAL_DBHOST: mariadb
      DRUPAL_DBPORT: 3306
      DRUPAL_DBUSER: drupal
      DRUPAL_DBPASS: drupal
      DRUPAL_DBNAME: drupal
      DRUPAL_MEMCACHE: true
      DRUPAL_MEMCACHEHOST: memcached
      PRIVATE_FILE_PATH: /mnt/files/private
    volumes:
    - ./:/var/www/html
    - ./private:/mnt/files/private

  solr:
    image: solr:8-slim
    expose:
      - 8983
    ports:
      - 8983:8983
    environment:
    - OOM=crash
    - SOLR_HEAP=2g
    command:
      - solr-precreate
      - drupal
    volumes:
    - solr:/var/solr
    - ./dev/solr_8.x_config/conf:/opt/solr/server/solr/configsets/_default/conf

  memcached:
    image: memcached:1.6-alpine

volumes:
  solr:
  mariadb: