<?php

/**
 * @file
 * The Main module file.
 */

/**
 * Implements hook_modules_installed().
 *
 * Once the Default content is imported we need to update the media_id for the
 * background image. This hook is called after every module is installed.
 * By checking for the module type and to ensure we are not in configuration
 * import step:
 *   - Load the media entity by UUID and get its ID.
 *   - Load the section library by UUID and update its settings by setting
 *     the media_id and save it back to the database.
 */
function osu_library_two_column_25_75_modules_installed($modules, $is_syncing) {
  if (in_array('osu_library_two_column_25_75', $modules) && !$is_syncing) {
    \Drupal::service('osu_default_content.library_media_update')::updateSectionLibrarySectionBackground('f5f32813-2eb8-49ac-b5d6-df111babdb7c', '3a0135f7-33d4-4355-b553-3dc0e420a531');
  }
}
