<?php

/**
 * @file
 * OSU Paragraphs Module File.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function osu_paragraphs_preprocess_paragraph__osu_tab_wrapper(&$variables) {
  // Attach the library to your specific paragraphs bundle.
  $variables['#attached']['library'][] = 'osu_paragraphs/vertical-tabs';
}

/**
 * Implements hook_theme().
 */
function osu_paragraphs_theme($existing, $type, $theme, $path) {
  // Need to register our paragraph templates here so they get picked up.
  return [
    'paragraph__osu_tab_content' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__osu_tab_wrapper' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function osu_paragraphs_theme_suggestions_paragraph_alter(array &$suggestions, array &$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  $bundle = $paragraph->bundle();
  $suggestions[] = 'paragraph__osu_paragraphs__' . $bundle;
}

